params:
  seed: ${...seed}
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    num_critics: 1
    shared_encoder: False
    critic_loss_mode: mean

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:FrankaPushing,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    multi_gpu: ${....multi_gpu}
    use_diagnostics: True
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-4
    lr_schedule: adaptive
    schedule_type: standard
    adaptive_lr_coef: 1.5
    kl_threshold: 0.008
    score_to_win: 10000
    max_epochs: ${resolve_default:50000,${....max_iterations}}
    save_best_after: 10
    save_frequency: 100
    test_every_episodes: 10
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 32
    num_minibatches: 32
    mini_epochs: 5
    critic_coef: 4
    clip_value: True
    seq_len: 4
    bounds_loss_coef: 0.0001
    critic_ensemble_mode: min
    critic_loss_mode: mean

  curriculum:
    enable: False
    vds:
      n_candidates: 1
      temperature: 1
      disagreement_fn_name: std
      visualize_every: 0
    goid:
      intermediate:
        lower: 0.1
        upper: 0.9
        max_sample_attempts: 10
      mlp:
        units: [256, 128, 64]
        activation: elu
        d2rl: False

        initializer:
          name: default
        regularizer:
          name: None
      config:
        batch_size: 256
        n_epochs: 10
        learning_rate: 5e-4
        success_metric: success_4
        collect_data: False
        visualize_every: 0